### ISSUE TITLE
How to move bookmarks?

### ISSUE THREAD

**Issue by CodingFan72** [sakethpathike/Linkora#10]
If I have saved a bookmark, how can I move it to another folder later?

**Comment by sakethpathike** [comment]
moving or copying links to folders isn't possible yet

**Comment by franco27** [comment]
I would also be interested in this feature. I just installed it, and if we can’t move or copy a link to another folder, I find that really unfortunate.

**Comment by sakethpathike** [comment]
@franco27 it will be added soon :)

**Comment by sakethpathike** [comment]
This has been implemented in the latest release v0.9.0: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.9.0
