### ISSUE TITLE
A default folder named "All links"

### ISSUE THREAD

**Issue by Zaxx69** [sakethpathike/Linkora#14]
please create a default folder named "all links" where all the links that is saved on the app will show ( even when the links are grouped ) . this folder will show all the links present

**Comment by sakethpathike** [comment]
this is already in development and will be available with the next major release (0.8.x)

**Comment by Zaxx69** [comment]
thank you

**Comment by sakethpathike** [comment]
This has been added in 0.8.0: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.8.0

**Comment by Zaxx69** [comment]
thank you
