### ISSUE TITLE
Ability to search words from notes too

### ISSUE THREAD

**Issue by Zaxx69** [sakethpathike/Linkora#15]
ability to search keywords from notes saved along with the links

**Comment by sakethpathike** [comment]
will be added in the next release :)

**Comment by Zaxx69** [comment]
thank you

**Comment by Zaxx69** [comment]
thank you

**Comment by sakethpathike** [comment]
Thank you for mentioning this :) This has been implemented in 0.8.0: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.8.0

**Comment by Zaxx69** [comment]
thank you for adding it
