### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [sakethpathike/Linkora#17]
[app-fdroid-release.apk.html.zip](https://github.com/user-attachments/files/17005590/app-fdroid-release.apk.html.zip)

Is your apk built from the tag? Can you try cleaning the cache and rebuilding it?

**Comment by sakethpathike** [comment]
> Is your apk built from the tag?

Yes. 

> Can you try cleaning the cache and rebuilding it?

I've updated it: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.7.2

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
can we reopen? ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7925026174#L1825

**Comment by sakethpathike** [comment]
Should I rebuild it using the same tag that was used to build 0.8.1 (29th version)?

**Comment by linsui** [comment]
Not sure if rebuild can fix it but we can have a try. :)

**Comment by sakethpathike** [comment]
I've updated it: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.8.1

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7950794004 In face 0.8.2 has been built reproducibly... 0.8.1 is also fixed but we'll just skip it. Thanks!
