### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by brimstonecrypt** [sakethpathike/Linkora#18]
![Screenshot_20240915_205005_Linkora](https://github.com/user-attachments/assets/fadc8697-4cf5-4b89-9fe3-2a8138dbb667)

How to change font?

**Comment by sakethpathike** [comment]
Okay, this is unusual 😅. It shouldn’t happen. Could you please uninstall and reinstall it from the releases page?

Make sure to export your links before uninstalling, and reimport them after reinstalling.

Here’s the link: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.7.2.

**Comment by brimstonecrypt** [comment]
I tried both the version but same issue.

**Comment by sakethpathike** [comment]
Thank you for mentioning this :) This has been fixed in 0.8.0: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.8.0

**Comment by brimstonecrypt** [comment]
Working perfectly👍
