### ISSUE TITLE
Themed Monochrome App Icon

### ISSUE THREAD

**Issue by NielSync** [sakethpathike/Linkora#2]
Please implement a themed/monochrome app icon.
![Screenshot_20240629-092730.jpg](https://github.com/sakethpathike/Linkora/assets/20804647/f32ebd35-9f04-4775-819a-cb8b7bb8ebc5)

**Comment by sakethpathike** [comment]
I've just started working on this, along with a few other fixes. I'll push the update within a few hours.

**Comment by sakethpathike** [comment]
Themed/monochrome app icons have been implemented in the [latest release](https://github.com/sakethpathike/Linkora/releases/tag/release-v0.5.0).

**Comment by sakethpathike** [comment]
Thanks for your suggestion @NielSync! The themed/monochrome app icon has been implemented in the [latest release](https://github.com/sakethpathike/Linkora/releases/tag/release-v0.5.0).
