### ISSUE TITLE
Auto-saving from copying clipboard

### ISSUE THREAD

**Issue by AdityaMH** [sakethpathike/Linkora#20]
Add feature that can automatically saving the link when copying. Then stored to default that can moved to folder.

**Comment by turmoil-preshow** [comment]
Even better would be a button to quickly paste without adding any other option/confirmation
(and removing the  - button that shows the panels, that should be an option under settings)

**Comment by sakethpathike** [comment]
Hello, @AdityaMH, I'm going to work on this now. If I understood correctly, whenever you copy a link outside Linkora, it should be auto-saved without manual input. Is that what you're saying?

**Comment by AdityaMH** [comment]
> Hello, @AdityaMH, I'm going to work on this now. If I understood correctly, whenever you copy a link outside Linkora, it should be auto-saved without manual input. Is that what you're saying?

Yeah

**Comment by sakethpathike** [comment]
Hello, @AdityaMH, this cannot be implemented as Android restricts access to the clipboard.

> Unless your app is the default [input method editor (IME)](https://developer.android.com/guide/topics/text/creating-input-method) or is the app that currently has focus, your app cannot access clipboard data on Android 10 or higher.

https://developer.android.com/about/versions/10/privacy/changes#clipboard-data
