### ISSUE TITLE
Automatic titles are weird

### ISSUE THREAD

**Issue by MathisP75** [sakethpathike/Linkora#23]
Automatic titles seem to be very hit or miss compared to Google Keep. Sometimes I get the generic website name only: ![Screenshot_20240923-082850.png](https://github.com/user-attachments/assets/b20a9d26-08c8-472d-80da-79a927959096)

![Screenshot_20240923-082914.png](https://github.com/user-attachments/assets/3c574dd5-b01c-4393-ac4a-519d081a9116)

Sometimes, I get weird stuff, like this Reddit title in an unknown language:![Screenshot_20240923-082827.png](https://github.com/user-attachments/assets/1b976c38-6fd1-4e2c-8265-b8dbdf2aa790)

![Screenshot_20240923-082815.png](https://github.com/user-attachments/assets/99917f9f-86ed-4310-a61f-d8b8b4e2c5d4)

**Comment by sakethpathike** [comment]
I've also noticed the issue with Reddit and other sites.

Titles and images are scraped from the website's meta tags in the HTML, so as long as they're present, the app will "fetch" them.

I'm not quite sure how Keep handles this, but I'll look into it soon.

**Comment by cris16228** [comment]
> Automatic titles seem to be very hit or miss compared to Google Keep. Sometimes I get the generic website name only: ![Screenshot_20240923-082850.png](https://private-user-images.githubusercontent.com/98901170/369872501-b20a9d26-08c8-472d-80da-79a927959096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzg5MTAsIm5iZiI6MTcyNzM3ODYxMCwicGF0aCI6Ii85ODkwMTE3MC8zNjk4NzI1MDEtYjIwYTlkMjYtMDhjOC00NzJkLTgwZGEtNzlhOTI3OTU5MDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNGRiYmE0MWU0YTFmNTJhMTNkZWIyYmM2YzA0MmVlNGIyZGIzZTI1NTYyNjg4YTE0N2YyN2Q1NGUzNTU5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dRa8L2XlCvClLjiiff0ZNlgSRu8yYMi3lusw1L3QJDQ)
> 
> ![Screenshot_20240923-082914.png](https://private-user-images.githubusercontent.com/98901170/369872535-3c574dd5-b01c-4393-ac4a-519d081a9116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzg5MTAsIm5iZiI6MTcyNzM3ODYxMCwicGF0aCI6Ii85ODkwMTE3MC8zNjk4NzI1MzUtM2M1NzRkZDUtYjAxYy00MzkzLWFjNGEtNTE5ZDA4MWE5MTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNzQ5MmZlYWY4NjQxMmNhYjJmNDM1ZDMyM2JhM2IwYmUxYjRlZjI2NTI1ZjQwNzQ2YzA3MmU1ZjNjOWRiYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZshouHnm5EPXNp6aHFKfz1wVykPrUDjEvpEu2bqa3Zs)
> 
> Sometimes, I get weird stuff, like this Reddit title in an unknown language:![Screenshot_20240923-082827.png](https://private-user-images.githubusercontent.com/98901170/369872724-1b976c38-6fd1-4e2c-8265-b8dbdf2aa790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzg5MTAsIm5iZiI6MTcyNzM3ODYxMCwicGF0aCI6Ii85ODkwMTE3MC8zNjk4NzI3MjQtMWI5NzZjMzgtNmZkMS00ZTJjLTgyNjUtYjhkYmRmMmFhNzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOGVhNWI1M2ExMzQyOGE0MDYxNGI0NzNiNDg2ZDhlYWRhZDQ1YWQxZDFiYzRmMTg4YzIxYjI0ZTBkYjBiODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7FFkmIPZtjQ-_fcStPDyF_MeLsDSGenesxIVEnri8O0)
> 
> ![Screenshot_20240923-082815.png](https://private-user-images.githubusercontent.com/98901170/369872748-99917f9f-86ed-4310-a61f-d8b8b4e2c5d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzg5MTAsIm5iZiI6MTcyNzM3ODYxMCwicGF0aCI6Ii85ODkwMTE3MC8zNjk4NzI3NDgtOTk5MTdmOWYtODZlZC00MzEwLWE2MWYtZDhiOGI0ZTJjNWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NzkyODZhYWJmY2E0ZWJlYmUyZjhmYjQxZGEyOWJiYzE0YjNkMDYyOTNjMTdhMmRmYjg5NmE2NzgzOTNhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pJw5Nmqpk4vknk2K4a1YFzoMIIPfE1TOLk8hbv7CdI4)

The latter with reddit is because he's using a simple html parser library. Basically, reddit, and some other sites, use basic html structure so the title you see (in italian) while loading the correct title of the post with javascript. Since the app uses only a simple HTML parser library, it will never loads dynamic pages like reddit. There are solutions (for the dev) but he has to implement them

**Comment by cris16228** [comment]
> Automatic titles seem to be very hit or miss compared to Google Keep. Sometimes I get the generic website name only: ![Screenshot_20240923-082850.png](https://private-user-images.githubusercontent.com/98901170/369872501-b20a9d26-08c8-472d-80da-79a927959096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzg5MTAsIm5iZiI6MTcyNzM3ODYxMCwicGF0aCI6Ii85ODkwMTE3MC8zNjk4NzI1MDEtYjIwYTlkMjYtMDhjOC00NzJkLTgwZGEtNzlhOTI3OTU5MDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNGRiYmE0MWU0YTFmNTJhMTNkZWIyYmM2YzA0MmVlNGIyZGIzZTI1NTYyNjg4YTE0N2YyN2Q1NGUzNTU5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dRa8L2XlCvClLjiiff0ZNlgSRu8yYMi3lusw1L3QJDQ)
> 
> ![Screenshot_20240923-082914.png](https://private-user-images.githubusercontent.com/98901170/369872535-3c574dd5-b01c-4393-ac4a-519d081a9116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzg5MTAsIm5iZiI6MTcyNzM3ODYxMCwicGF0aCI6Ii85ODkwMTE3MC8zNjk4NzI1MzUtM2M1NzRkZDUtYjAxYy00MzkzLWFjNGEtNTE5ZDA4MWE5MTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNzQ5MmZlYWY4NjQxMmNhYjJmNDM1ZDMyM2JhM2IwYmUxYjRlZjI2NTI1ZjQwNzQ2YzA3MmU1ZjNjOWRiYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZshouHnm5EPXNp6aHFKfz1wVykPrUDjEvpEu2bqa3Zs)
> 
> Sometimes, I get weird stuff, like this Reddit title in an unknown language:![Screenshot_20240923-082827.png](https://private-user-images.githubusercontent.com/98901170/369872724-1b976c38-6fd1-4e2c-8265-b8dbdf2aa790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzg5MTAsIm5iZiI6MTcyNzM3ODYxMCwicGF0aCI6Ii85ODkwMTE3MC8zNjk4NzI3MjQtMWI5NzZjMzgtNmZkMS00ZTJjLTgyNjUtYjhkYmRmMmFhNzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOGVhNWI1M2ExMzQyOGE0MDYxNGI0NzNiNDg2ZDhlYWRhZDQ1YWQxZDFiYzRmMTg4YzIxYjI0ZTBkYjBiODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7FFkmIPZtjQ-_fcStPDyF_MeLsDSGenesxIVEnri8O0)
> 
> ![Screenshot_20240923-082815.png](https://private-user-images.githubusercontent.com/98901170/369872748-99917f9f-86ed-4310-a61f-d8b8b4e2c5d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzg5MTAsIm5iZiI6MTcyNzM3ODYxMCwicGF0aCI6Ii85ODkwMTE3MC8zNjk4NzI3NDgtOTk5MTdmOWYtODZlZC00MzEwLWE2MWYtZDhiOGI0ZTJjNWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NzkyODZhYWJmY2E0ZWJlYmUyZjhmYjQxZGEyOWJiYzE0YjNkMDYyOTNjMTdhMmRmYjg5NmE2NzgzOTNhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pJw5Nmqpk4vknk2K4a1YFzoMIIPfE1TOLk8hbv7CdI4)

The latter with reddit is because he's using a simple html parser library.
Dm'd the dev. Hoping to hear back for updates!


Edit: Both your problems are the one I've said above

**Comment by sakethpathike** [comment]
Hello, @MathisP75, try changing the user agent to `Twitterbot/1.0` in the app settings and reloading the link info. This should fix most title and image detection issues. However, some images, especially from Reddit, might not load as expected. I will fix this in the soon.

**Comment by MathisP75** [comment]
That did it, thank you!

**Comment by sakethpathike** [comment]
This has been fixed in v0.8.2: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.8.2.

Thanks for raising this issue, @MathisP75!

@cris16228 🙌
