### ISSUE TITLE
App v7.2 thinks it is v7.1

### ISSUE THREAD

**Issue by plutonium-239** [sakethpathike/Linkora#24]
Images explain it better: 

In-app:
![Screenshot_20240923-222507_Linkora.png](https://github.com/user-attachments/assets/a051b93d-1434-4fda-9a1a-bf7e0cb1c46c)

Droidify (F-Droid client):
![Screenshot_20240923-222037_1.jpg](https://github.com/user-attachments/assets/bf81178e-92a7-40a1-b1d7-146d08c8332d)

**Comment by sakethpathike** [comment]
I probably forgot to change the version name for the F-Droid flavor 😅;

This has been fixed in 0.8.0: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.8.0
