### ISSUE TITLE
[BUG] "Remove from important links" behaves like "delete link"

### ISSUE THREAD

**Issue by turmoil-preshow** [sakethpathike/Linkora#25]
Removing a favorite link from the _saved links_ tab will delete the link from the _saved links_ tab, but won't remove it from the favorites tab.
see attachment. 

https://github.com/user-attachments/assets/22c4cec7-dd6d-4c7f-ad2e-a2958745273b

Android 14, release-v0.8.0

**Comment by sakethpathike** [comment]
will release the fix ASAP

**Comment by sakethpathike** [comment]
This has been fixed in 0.8.1: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.8.1
