### ISSUE TITLE
About new language translations 

### ISSUE THREAD

**Issue by egmsia01** [sakethpathike/Linkora#27]
I noticed that there is some content involving string stitching in the project, but the word order in some languages is different from English. I'm not sure how to deal with it properly.

For example：
- In English:
 `{string$0} can be accessed from the {string$1}`
- In Chinese:
`{string$0}可以通过{string$1}进行访问`

Emmm...The relative positions of fill characters are different.

In this case, how can I provide the translation in the correct format in `Crowdin` to ensure that there will be no errors in word order when filling the string?

Thank you！

**Comment by egmsia01** [comment]
ohhh...sorry, I overlooked a few things in the documentation. I think I've solved the problem.
Thank you

**Comment by sakethpathike** [comment]
Thank you for taking the time to add those; I appreciate it.
