### ISSUE TITLE
The Export feature not working 

### ISSUE THREAD

**Issue by Himanshu-369** [sakethpathike/Linkora#28]
I want to export the saved links, but when I pressed the Export Data Button it just showed a pop-up "Successfully Exported" but can't find the exported json file. Just want to know where it is saved.

**Comment by sakethpathike** [comment]
> I want to export the saved links

You cannot specifically export `Saved Links`; everything (excluding `Panels`) gets exported based on the _Linkora Schema_. The Import/Export feature is being rewritten, and you can make specific exports once they are available.

> where is it saved

Documents -> Linkora -> Exports
