### ISSUE TITLE
Feature Request: Add option to not fetch metadata

### ISSUE THREAD

**Issue by Ignema** [sakethpathike/Linkora#35]
Hello, thank you for making the Linkora app. It's very useful and it has a ton if potential.

One thing that would improve my workflow in creating links in the app is to disable the metadata fetching because I usually save  video direct links.

When I try to save a direct link to a video, the application takes time sending multiple requests using the two configured user agents but it will never find anything because it's not a web page.

**Comment by sakethpathike** [comment]
Currently working on this; it will be available in the next update :)

**Comment by sakethpathike** [comment]
This has been added in the latest release: https://github.com/sakethpathike/Linkora/releases/tag/release-v0.10.0
