### ISSUE TITLE
用户界面没数据，也不知道在哪里导入数据

### ISSUE THREAD

**Issue by 307373045** [sakethpathike/Linkora#6]
关键在于app界面一串串English，看不懂，能否搞个中文版的出来？
我初学andorid的，不知到时你的项目值不值得研究

**Comment by sakethpathike** [comment]
你需要在应用程序中添加链接，并在需要时进行整理。目前没有云集成，因此你必须手动导出数据，并导入同样的导出文件，这个文件遵循 Linkora 特定的格式。

对于中文版，我会尝试在下一个版本中添加。是的，你可以 fork 这个仓库或从 Android Studio 克隆，并根据你的需求进行修改。

至于“研究”这个仓库，代码目前有些混乱，但你应该能够理解发生了什么，如果有任何不明白的地方，请告诉我。

**Comment by 307373045** [comment]
好的  Thanks
