### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by cris16228** [sakethpathike/Linkora#9]
https://github.com/user-attachments/assets/71708475-4b72-4df0-a785-461bb7ff2e75

I thinking it's self explanatory. It crashes whenever you click on the link item (where buttons, icon  title is)

**Comment by sakethpathike** [comment]
Do you have the "use in-app browser" option enabled? If so, is Chrome disabled on your device?

This issue occurs only when Chrome is disabled, as the app only checks for Chrome. This will be fixed in the next release.

**Comment by cris16228** [comment]
> Do you have the "use in-app browser" option enabled? If so, is Chrome disabled on your device?
> 
> This issue occurs only when Chrome is disabled, as the app only checks for Chrome. This will be fixed in the next release.

Yes because I hate chrome. Why does it only checks/uses chrome? What about other browsers?

**Comment by sakethpathike** [comment]
> Why does it only check/use Chrome?

It was previously hardcoded only to use Chrome.

> What about other browsers?

It only targeted Chrome and did not check other browsers.

This issue has been fixed in the [latest release](https://github.com/sakethpathike/Linkora/releases/tag/release-v0.7.2) :))
